# Generated by Django 3.2.10 on 2023-03-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0002_auto_20230325_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
    ]
