# Generated by Django 3.2.10 on 2023-03-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0003_remove_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='nombreusuario',
            field=models.CharField(default=int, max_length=90),
            preserve_default=False,
        ),
    ]
