# Generated by Django 3.2.10 on 2023-03-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0004_lineapedido_nombreusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='nombreusuario',
        ),
    ]
