# Generated by Django 3.2.10 on 2023-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0005_remove_lineapedido_nombreusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='nombreusuario',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
