# Generated by Django 3.2.10 on 2023-03-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0007_remove_lineapedido_nombreusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='id_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_user',
            field=models.IntegerField(default=1),
        ),
    ]
