# Generated by Django 3.2.10 on 2023-03-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0008_auto_20230326_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_user',
        ),
    ]
