# Generated by Django 3.2.10 on 2023-03-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0009_auto_20230326_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineaPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
