# Generated by Django 3.2.10 on 2023-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0011_lineapedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='precio',
            field=models.IntegerField(default=1),
        ),
    ]
