# Generated by Django 3.2.10 on 2023-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0012_lineapedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='total',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='precio',
            field=models.FloatField(default=1),
        ),
    ]
