# Generated by Django 3.2.10 on 2023-03-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0013_auto_20230328_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='total',
        ),
    ]
