# Generated by Django 3.2.10 on 2023-03-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCast', '0014_remove_lineapedido_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='correo',
            name='empresa',
        ),
    ]
